# Generated by Django 3.2.8 on 2021-10-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimBodytype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('body_type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Dim.BodyType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimClubs',
            fields=[
                ('clubid', models.IntegerField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Dim.Clubs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCountry',
            fields=[
                ('countryid', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Dim.Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimLeagues',
            fields=[
                ('leagueid', models.IntegerField(primary_key=True, serialize=False)),
                ('league', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'Dim.Leagues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPlayers',
            fields=[
                ('sofifa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=200)),
                ('long_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
            ],
            options={
                'db_table': 'Dim.Players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPositions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Dim.Positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPreferredfoot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('preferred_foot', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Dim.PreferredFoot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimRealface',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('real_face', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Dim.RealFace',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimWorkrate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('work_rate', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Dim.WorkRate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactPlayerpositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sofifa_id', models.IntegerField()),
                ('position', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'Fact.PlayerPositions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactPlayerstats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sofifa_id', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('player_url', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('height_cm', models.CharField(blank=True, max_length=50, null=True)),
                ('weight_kg', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('club_name', models.CharField(blank=True, max_length=50, null=True)),
                ('league_name', models.CharField(blank=True, max_length=50, null=True)),
                ('league_rank', models.CharField(blank=True, max_length=50, null=True)),
                ('overall', models.CharField(blank=True, max_length=50, null=True)),
                ('potential', models.CharField(blank=True, max_length=50, null=True)),
                ('value_eur', models.CharField(blank=True, max_length=50, null=True)),
                ('wage_eur', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_foot', models.CharField(blank=True, max_length=50, null=True)),
                ('international_reputation', models.CharField(blank=True, max_length=50, null=True)),
                ('weak_foot', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_moves', models.CharField(blank=True, max_length=50, null=True)),
                ('work_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('real_face', models.CharField(blank=True, max_length=50, null=True)),
                ('release_clause_eur', models.CharField(blank=True, max_length=50, null=True)),
                ('player_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('team_position', models.CharField(blank=True, max_length=50, null=True)),
                ('team_jersey_number', models.CharField(blank=True, max_length=50, null=True)),
                ('loaned_from', models.CharField(blank=True, max_length=50, null=True)),
                ('joined', models.DateField(blank=True, null=True)),
                ('contract_valid_until', models.CharField(blank=True, max_length=50, null=True)),
                ('nation_position', models.CharField(blank=True, max_length=50, null=True)),
                ('nation_jersey_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pace', models.CharField(blank=True, max_length=50, null=True)),
                ('shooting', models.CharField(blank=True, max_length=50, null=True)),
                ('passing', models.CharField(blank=True, max_length=50, null=True)),
                ('dribbling', models.CharField(blank=True, max_length=50, null=True)),
                ('defending', models.CharField(blank=True, max_length=50, null=True)),
                ('physic', models.CharField(blank=True, max_length=50, null=True)),
                ('gk_diving', models.CharField(blank=True, max_length=50, null=True)),
                ('gk_handling', models.CharField(blank=True, max_length=50, null=True)),
                ('gk_kicking', models.CharField(blank=True, max_length=50, null=True)),
                ('gk_reflexes', models.CharField(blank=True, max_length=50, null=True)),
                ('gk_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('gk_positioning', models.CharField(blank=True, max_length=50, null=True)),
                ('player_traits', models.CharField(blank=True, max_length=200, null=True)),
                ('attacking_crossing', models.CharField(blank=True, max_length=50, null=True)),
                ('attacking_finishing', models.CharField(blank=True, max_length=50, null=True)),
                ('attacking_heading_accuracy', models.CharField(blank=True, max_length=50, null=True)),
                ('attacking_short_passing', models.CharField(blank=True, max_length=50, null=True)),
                ('attacking_volleys', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_dribbling', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_curve', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_fk_accuracy', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_long_passing', models.CharField(blank=True, max_length=50, null=True)),
                ('skill_ball_control', models.CharField(blank=True, max_length=50, null=True)),
                ('movement_acceleration', models.CharField(blank=True, max_length=50, null=True)),
                ('movement_sprint_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('movement_agility', models.CharField(blank=True, max_length=50, null=True)),
                ('movement_reactions', models.CharField(blank=True, max_length=50, null=True)),
                ('movement_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('power_shot_power', models.CharField(blank=True, max_length=50, null=True)),
                ('power_jumping', models.CharField(blank=True, max_length=50, null=True)),
                ('power_stamina', models.CharField(blank=True, max_length=50, null=True)),
                ('power_strength', models.CharField(blank=True, max_length=50, null=True)),
                ('power_long_shots', models.CharField(blank=True, max_length=50, null=True)),
                ('mentality_aggression', models.CharField(blank=True, max_length=50, null=True)),
                ('mentality_interceptions', models.CharField(blank=True, max_length=50, null=True)),
                ('mentality_positioning', models.CharField(blank=True, max_length=50, null=True)),
                ('mentality_vision', models.CharField(blank=True, max_length=50, null=True)),
                ('mentality_penalties', models.CharField(blank=True, max_length=50, null=True)),
                ('mentality_composure', models.CharField(blank=True, max_length=50, null=True)),
                ('defending_marking', models.CharField(blank=True, max_length=50, null=True)),
                ('defending_standing_tackle', models.CharField(blank=True, max_length=50, null=True)),
                ('defending_sliding_tackle', models.CharField(blank=True, max_length=50, null=True)),
                ('goalkeeping_diving', models.CharField(blank=True, max_length=50, null=True)),
                ('goalkeeping_handling', models.CharField(blank=True, max_length=50, null=True)),
                ('goalkeeping_kicking', models.CharField(blank=True, max_length=50, null=True)),
                ('goalkeeping_positioning', models.CharField(blank=True, max_length=50, null=True)),
                ('goalkeeping_reflexes', models.CharField(blank=True, max_length=50, null=True)),
                ('ls', models.CharField(blank=True, max_length=50, null=True)),
                ('st', models.CharField(blank=True, max_length=50, null=True)),
                ('rs', models.CharField(blank=True, max_length=50, null=True)),
                ('lw', models.CharField(blank=True, max_length=50, null=True)),
                ('lf', models.CharField(blank=True, max_length=50, null=True)),
                ('cf', models.CharField(blank=True, max_length=50, null=True)),
                ('rf', models.CharField(blank=True, max_length=50, null=True)),
                ('rw', models.CharField(blank=True, max_length=50, null=True)),
                ('lam', models.CharField(blank=True, max_length=50, null=True)),
                ('cam', models.CharField(blank=True, max_length=50, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('lm', models.CharField(blank=True, max_length=50, null=True)),
                ('lcm', models.CharField(blank=True, max_length=50, null=True)),
                ('cm', models.CharField(blank=True, max_length=50, null=True)),
                ('rcm', models.CharField(blank=True, max_length=50, null=True)),
                ('rm', models.CharField(blank=True, max_length=50, null=True)),
                ('lwb', models.CharField(blank=True, max_length=50, null=True)),
                ('ldm', models.CharField(blank=True, max_length=50, null=True)),
                ('cdm', models.CharField(blank=True, max_length=50, null=True)),
                ('rdm', models.CharField(blank=True, max_length=50, null=True)),
                ('rwb', models.CharField(blank=True, max_length=50, null=True)),
                ('lb', models.CharField(blank=True, max_length=50, null=True)),
                ('lcb', models.CharField(blank=True, max_length=50, null=True)),
                ('cb', models.CharField(blank=True, max_length=50, null=True)),
                ('rcb', models.CharField(blank=True, max_length=50, null=True)),
                ('rb', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Fact.PlayerStats',
                'managed': False,
            },
        ),
    ]
